language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm]

env:
  - SYMFONY_VERSION=

matrix:
  fast_finish: true
  include:
  - { php: 5.3.3, env: "SYMFONY_VERSION=2.3.*" }
  - { php: 5.4,   env: "SYMFONY_VERSION=2.4.*" }
  - { php: 5.5,   env: "SYMFONY_VERSION=2.5.*" }
  - { php: 5.6,   env: "SYMFONY_VERSION=2.6.*" }
  - { php: 5.6,   env: "SYMFONY_VERSION=2.7.*" }
  - { php: 5.3.3, env: "COMPOSER_LOWEST_VERSION=Y" }
  - { php: 5.4,   env: "COMPOSER_LOWEST_VERSION=Y SYMFONY_VERSION=2.4.*" }
  - { php: 5.5,   env: "COMPOSER_LOWEST_VERSION=Y SYMFONY_VERSION=2.5.*" }
  - { php: 5.6,   env: "COMPOSER_LOWEST_VERSION=Y SYMFONY_VERSION=2.6.*" }
  allow_failures:
  - { php: hhvm }

install:
  - npm install grunt-cli -g
  - npm install
  - composer self-update

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - sh -c 'if [ "$COMPOSER_LOWEST_VERSION" != "" ]; then composer update --prefer-lowest --prefer-stable --dev; else composer install --dev; fi;'
  - mkdir -p build/logs
  - wget https://phar.phpunit.de/phpunit.phar

script:
  - php phpunit.phar --coverage-text --coverage-clover=coverage.clover
  - grunt test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
  - $HOME/.composer/
