language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm]

matrix:
  include:
  - { php: 5.3.3, env: "SYMFONY_VERSION=2.3.*" }
  - { php: 5.5,   env: "SYMFONY_VERSION=2.5.*" }
  - { php: 5.6,   env: "SYMFONY_VERSION=2.6.*" }
  - { php: 5.6,   env: "SYMFONY_VERSION=2.7.*" }
  - { php: 5.3.3, env: "COMPOSER_FLAGS='--prefer-stable --prefer-lowest' PHPUNIT_COVERAGE='--coverage-text --coverage-clover=coverage.clover'"}
  allow_failures:
  - { php: hhvm }

before_script:
  # Install npm deps
  - travis_retry npm install grunt-cli -g
  - travis_retry npm install
  # Update composer and deps
  - sh -c 'if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update symfony/symfony=${SYMFONY_VERSION}; fi;'
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit ${PHPUNIT_COVERAGE}
  - grunt test

after_script:
  - if [[ "${PHPUNIT_COVERAGE}" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "${PHPUNIT_COVERAGE}" != "" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
  - $HOME/.composer/
