language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm]

env:
  - SYMFONY_VERSION=2.3.*

matrix:
  fast_finish: true
  include:
  - { php: 5.3.3, env: "" }
  - { php: 5.3.3, env: "SYMFONY_VERSION=2.3.* TWIG_VERSION=1.15" }
  - { php: 5.4,   env: "SYMFONY_VERSION=2.4.*" }
  - { php: 5.5,   env: "SYMFONY_VERSION=2.5.*" }
  - { php: 5.6,   env: "SYMFONY_VERSION=2.6.*" }
  allow_failures:
  - { php: hhvm }

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - sh -c 'if [ "$TWIG_VERSION" != "" ]; then composer require --no-update twig/twig=$TWIG_VERSION; fi;'
  - composer install --dev
  - mkdir -p build/logs
  - wget https://phar.phpunit.de/phpunit.phar

script:
  - php phpunit.phar --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
  - $HOME/.composer/
