parameters:
  boekkooi.jquery_validation.form.form_extension.class: Boekkooi\Bundle\JqueryValidationBundle\Form\Extension\FormTypeExtension

  boekkooi.jquery_validation.rule_collector.class: Boekkooi\Bundle\JqueryValidationBundle\Form\RuleCollector
  boekkooi.jquery_validation.constraint_finder.class: Boekkooi\Bundle\JqueryValidationBundle\Form\DataConstraintFinder
  boekkooi.jquery_validation.constraint_resolver.class: Boekkooi\Bundle\JqueryValidationBundle\Form\Rule\ConstraintResolver

services:
  boekkooi.jquery_validation.form.form_extension:
    class: %boekkooi.jquery_validation.form.form_extension.class%
    arguments:
      - @boekkooi.jquery_validation.constraint_finder
      - @boekkooi.jquery_validation.rule_collector
      - %boekkooi.jquery_validation.enabled%
    tags:
      - { name: form.type_extension, alias: form }

  boekkooi.jquery_validation.rule_collector:
    class: %boekkooi.jquery_validation.rule_collector.class%
    arguments:
      - []

  boekkooi.jquery_validation.constraint_finder:
    class: %boekkooi.jquery_validation.constraint_finder.class%
    arguments:
      - @validator.mapping.class_metadata_factory

  boekkooi.jquery_validation.constraint_resolver:
    class: %boekkooi.jquery_validation.constraint_resolver.class%
    public: false
